# Generated by Django 4.0.6 on 2022-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailVerifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("code", models.CharField(max_length=6, verbose_name="인증번호")),
                ("token", models.CharField(max_length=40, verbose_name="토큰")),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PhoneVerifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("phone", models.CharField(max_length=11, verbose_name="휴대폰번호")),
                ("code", models.CharField(max_length=6, verbose_name="인증번호")),
                ("token", models.CharField(max_length=40, verbose_name="토큰")),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
