# Generated by Django 4.1.4 on 2023-01-26 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneverifier",
            name="phone",
            field=models.CharField(
                max_length=11,
                validators=[django.core.validators.validate_integer, django.core.validators.MinLengthValidator(10)],
                verbose_name="휴대폰번호",
            ),
        ),
    ]
