# Generated by Django 5.2 on 2025-12-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("username", models.CharField(max_length=100, unique=True, verbose_name="유저네임")),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                (
                    "social_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kakao", "카카오"),
                            ("naver", "네이버"),
                            ("facebook", "페이스북"),
                            ("google", "구글"),
                            ("apple", "애플"),
                        ],
                        editable=False,
                        max_length=10,
                        null=True,
                        verbose_name="소셜",
                    ),
                ),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저",
                "db_table": "user",
            },
        ),
    ]
