# Generated by Django 4.2.3 on 2023-07-24 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="user_set",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name="참여자"),
        ),
    ]
