# Generated by Django 4.1.4 on 2023-01-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="alarmtalklog",
            table="alarm_talk_log",
        ),
        migrations.AlterModelTable(
            name="emaillog",
            table="email_log",
        ),
        migrations.AlterModelTable(
            name="phonelog",
            table="phone_log",
        ),
        migrations.AlterModelTable(
            name="pushlog",
            table="push_log",
        ),
        migrations.AlterModelTable(
            name="tasklog",
            table="task_log",
        ),
    ]
