# Generated by Django 5.2 on 2025-12-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "탈퇴한 유저",
                "verbose_name_plural": "탈퇴한 유저",
                "db_table": "withdrawal_user",
                "ordering": ["-created_at"],
            },
            bases=("user.user",),
        ),
    ]
