# Generated by Django 4.1.4 on 2023-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeleryLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("name", models.CharField(max_length=100, verbose_name="태스크 명")),
                ("task_id", models.CharField(max_length=36, verbose_name="태스크 ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "대기"), ("SUCCESS", "성공"), ("FAILURE", "실패")],
                        default="PENDING",
                        max_length=10,
                        verbose_name="태스크 상태",
                    ),
                ),
                ("message", models.TextField(blank=True, default="", verbose_name="메세지")),
            ],
            options={
                "verbose_name": "셀러리 로그",
                "verbose_name_plural": "셀러리 로그",
                "db_table": "celery_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
