# Generated by Django 5.2 on 2025-12-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=20, unique=True, verbose_name="유저네임")),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                ("name", models.CharField(blank=True, max_length=20, null=True, verbose_name="이름")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="이메일")),
                ("phone", models.CharField(blank=True, max_length=11, null=True, verbose_name="휴대폰")),
            ],
            options={
                "verbose_name": "관리자",
                "verbose_name_plural": "관리자",
                "db_table": "admin_user",
            },
        ),
    ]
