# Generated by Django 4.2.3 on 2025-11-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminuser",
            name="last_login",
        ),
    ]
