# Generated by Django 4.2.3 on 2025-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_user", "0002_remove_adminuser_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="이메일"),
        ),
    ]
