AWSTemplateFormatVersion: '2010-09-09'

Description:
  'DDB IaC'

Parameters:
  ProjectName:
    Type: String
  ENV:
    Type: String
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref ENV, 'prod']

Resources:
  ConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${ENV}-connection-table'
      AttributeDefinitions:
        - AttributeName: connection_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

Outputs:
  ConnectionTable:
    Value: !Ref ConnectionTable
    Export:
      Name: '${ProjectName}-${ENV}-ConnectionTable'
  ConnectionTableArn:
    Value: !GetAtt ConnectionTable.Arn
    Export:
      Name: '${ProjectName}-${ENV}-ConnectionTableArn'