AWSTemplateFormatVersion: '2010-09-09'

Description:
  'DDB IaC'

Parameters:
  ProjectName:
    Type: String
  ENV:
    Type: String
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref ENV, 'prod']

Resources:
  HttpAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${ProjectName}-${ENV}-http-api'
      ProtocolType: HTTP
      RouteSelectionExpression: $request.body.action

  WebsocketAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${ProjectName}-${ENV}-websocket-api'
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketAPI
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Join ["/", ["integrations", !Ref ConnectIntegration]]
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketAPI
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Join ["/", ["integrations", !Ref DisconnectIntegration]]
  SendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketAPI
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Join ["/", ["integrations", !Ref SendIntegration]]

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    DependsOn: ConnectFunction
    Properties:
      ApiId: !Ref WebsocketAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ConnectFunction.Arn
  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    DependsOn: DisconnectFunction
    Properties:
      ApiId: !Ref WebsocketAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt DisconnectFunction.Arn
  SendIntegration:
    Type: AWS::ApiGatewayV2::Integration
    DependsOn: SendFunction
    Properties:
      ApiId: !Ref WebsocketAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt SendFunction.Arn

  ConnectFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WebsocketConnectLambda
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Handler: connect.lambda_handler
      Code:
        ZipFile: |
          import boto3
          import os

          db = boto3.client("dynamodb")


          def lambda_handler(event, context):
              print(event)
              print(context)

              db.put_item(
                  TableName=os.getenv("TABLE_NAME"),
                  Item={
                      "connection_id": {"S": event["requestContext"]["connectionId"]},
                      # "user_id": {"N": event['body']}
                  },
              )

              return {}

      Environment:
        Variables:
          TABLE_NAME: { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-ConnectionTable' }
  DisconnectFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WebsocketDisconnectLambda
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Handler: disconnect.lambda_handler
      Code:
        ZipFile: |
          import boto3
          import os

          db = boto3.client("dynamodb")


          def lambda_handler(event, context):
              print(event)
              print(context)

              db.delete_item(
                  TableName=os.getenv("TABLE_NAME"),
                  Key={"connection_id": {"S": event["requestContext"]["connectionId"]}},
              )

              return {}

      Environment:
        Variables:
          TABLE_NAME: { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-ConnectionTable' }
  SendFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WebsocketSendLambda
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Handler: send.lambda_handler
      Code:
        ZipFile: |
          import json

          import boto3
          import os

          db = boto3.client("dynamodb")


          def lambda_handler(event, context):
              print(event)
              print(context)

              message = json.loads(event["body"])["message"]

              items = db.query(
                  TableName=os.getenv("TABLE_NAME"),
                  IndexName="UserIdIndex",
                  KeyConditionExpression="user_id = :user_id",
                  ExpressionAttributeValues={
                      ":user_id": {"N": str(event["body"]["user_id"])},
                  },
              )

              api = boto3.client(
                  "apigatewaymanagementapi",
                  endpoint_url=f"https://{event['requestContext']['domainName']}/{event['requestContext']['stage']}",
              )
              for item in items:
                  api.post_to_connection(
                      ConnectionId=item["connectionId"],
                      Data=message,
                  )

              return {}

      Environment:
        Variables:
          TABLE_NAME: {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-ConnectionTable'}

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource: {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-ConnectionTableArn'}
              - Effect: Allow
                Action:
                  - 'execute-api:ManageConnections'
                Resource:
                  - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketAPI}/*'
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - SendRoute
    Properties:
      ApiId: !Ref WebsocketAPI
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: !Ref ENV
      DeploymentId: !Ref Deployment
      ApiId: !Ref WebsocketAPI
