# Generated by Django 5.2 on 2025-12-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsocketConnection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("id", models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name="id")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "웹소켓 연결",
                "verbose_name_plural": "웹소켓 연결",
                "db_table": "websocket_connection",
                "ordering": ["-created_at"],
            },
        ),
    ]
