# Generated by Django 4.1.4 on 2023-01-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="device",
            table="device",
        ),
    ]
